import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next.js Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="nav flex justify-between">
          <h1 className="bg-green-500 px-[20px] w-[35%]">
              <Link href="/list2">logo</Link>
          </h1>
          <ul className="bg-amber-300 px-[20px] w-[65%] flex gap-[20px] justify-end">
              <li><Link href="/info">info</Link></li>
              <li><Link href="/hihi">login</Link></li>
          </ul>
      </nav>
      <div className="container w-[600px] my-[0] mx-[auto]">
        {children}
      </div>
      </body>
    </html>
  );
}
